# Generated by Django 2.1.4 on 2021-10-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstagramApp', '0004_auto_20211017_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
