# Generated by Django 2.1.4 on 2021-10-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstagramApp', '0007_auto_20211017_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='default name', max_length=30, unique=True),
        ),
    ]
