# Generated by Django 2.1.4 on 2021-10-21 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InstagramApp', '0010_auto_20211021_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='comments',
        ),
    ]
