# Generated by Django 2.1.4 on 2021-10-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstagramApp', '0012_auto_20211022_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='Phone_num',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='image',
            name='email',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
