# Generated by Django 2.1.4 on 2021-10-29 07:19

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstagramApp', '0013_auto_20211029_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='Phone_num',
        ),
        migrations.RemoveField(
            model_name='image',
            name='email',
        ),
        migrations.AddField(
            model_name='profile',
            name='Phone_num',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_photo'),
        ),
    ]
