# Generated by Django 2.1.4 on 2021-11-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstagramApp', '0014_auto_20211029_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='caption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='landingpage',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='image',
            name='link',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
