# Generated by Django 2.1.4 on 2021-11-01 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InstagramApp', '0015_auto_20211101_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.IntegerField()),
                ('usability', models.IntegerField()),
                ('content', models.IntegerField()),
                ('image', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='InstagramApp.Image')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='InstagramApp.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
