# Generated by Django 2.1.4 on 2021-11-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstagramApp', '0018_auto_20211101_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
