# Generated by Django 2.1.4 on 2021-11-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstagramApp', '0021_rate_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='content',
            field=models.IntegerField(blank=True, default=0, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='design',
            field=models.IntegerField(blank=True, default=0, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='total',
            field=models.IntegerField(blank=True, default=0, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='usability',
            field=models.IntegerField(blank=True, default=0, max_length=30, null=True),
        ),
    ]
