# Generated by Django 2.1.4 on 2021-11-05 08:26

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstagramApp', '0022_auto_20211101_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landingpage', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('Name', models.CharField(max_length=30)),
                ('location', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('Occupants', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
