# Generated by Django 2.1.4 on 2021-11-05 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InstagramApp', '0023_neighbourhood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='landingpage',
            new_name='Businessimage',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='title',
            new_name='name',
        ),
    ]
